//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class forecasthour
    {
        public long Id { get; set; }
        public long forecastday_id { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<decimal> temp { get; set; }
        public string condition { get; set; }
        public Nullable<decimal> wind_speed { get; set; }
        public string wind_direction { get; set; }
        public Nullable<decimal> pressure { get; set; }
        public Nullable<int> humidity { get; set; }
        public Nullable<int> cloud_coverage { get; set; }
        public Nullable<decimal> visibility { get; set; }
        public Nullable<bool> rain { get; set; }
        public Nullable<bool> snow { get; set; }
    
        public virtual forecastday forecastday { get; set; }
    }
}
