//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class forecastday
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public forecastday()
        {
            this.forecasthour = new HashSet<forecasthour>();
        }
    
        public long Id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<decimal> max_temp { get; set; }
        public Nullable<decimal> min_temp { get; set; }
        public Nullable<decimal> avg_temp { get; set; }
        public Nullable<decimal> max_wind { get; set; }
        public Nullable<decimal> min_wind { get; set; }
        public Nullable<decimal> avg_wind { get; set; }
        public Nullable<decimal> total_precision { get; set; }
        public Nullable<decimal> avg_visibility { get; set; }
        public Nullable<int> avg_humidity { get; set; }
        public string condition { get; set; }
        public Nullable<System.DateTime> sunrise { get; set; }
        public Nullable<System.DateTime> sunset { get; set; }
        public Nullable<System.DateTime> moonrise { get; set; }
        public Nullable<System.DateTime> moonset { get; set; }
        public string moonphase { get; set; }
        public Nullable<int> moon_illumination { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<forecasthour> forecasthour { get; set; }
    }
}
