//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherAppAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeatherApp_dbEntities : DbContext
    {
        public WeatherApp_dbEntities()
            : base("name=WeatherApp_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<forecastday> forecastday { get; set; }
        public virtual DbSet<forecasthour> forecasthour { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<location> location { get; set; }
        public virtual DbSet<authToken> authToken { get; set; }
    }
}
